package com.rapidfix.technician.entity;
public enum ServiceType {
    ELECTRICIAN, PLUMBER, AC_REPAIR, CARPENTER, PAINTER, CLEANER, APPLIANCE_REPAIR, PEST_CONTROL,
    TAILORING, NETWORKING_TECH, BEAUTICIAN, MEHANDI_SERVICES, GENERAL_HELPER
}
